<?php 
# Code generated by sdkgen
# Generated on 2025-04-08 20:28:47.560715719 +0000 UTC using container gcr.io/repcore-prod/sdkgen:16.115.0
# DO NOT EDIT!

namespace Vendasta\GSuite\V1\internal;

interface DomainServiceClientInterface
{ 
    /**
     * Auth wrapper for \GSuite\V1\DomainServiceClient::VerifyDomain
     * @param \Gsuite\V1\VerifyDomainRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\VerifyDomainResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function VerifyDomain(\Gsuite\V1\VerifyDomainRequest $req, array $options = []): \Gsuite\V1\VerifyDomainResponse;
    
}
