<?php 
# Code generated by sdkgen
# Generated on 2025-04-08 20:28:47.560715719 +0000 UTC using container gcr.io/repcore-prod/sdkgen:16.115.0
# DO NOT EDIT!

namespace Vendasta\GSuite\V1\internal;

use Vendasta\Vax\GRPCClient;

class DomainServiceGRPCClient extends GRPCClient implements DomainServiceClientInterface
{
    private $client;

    /**
     * Constructor for DomainServiceGRPCClient
     * @param string $hostname hostname of the service to hit
     * @param string $scope
     * @param bool $secure
     * @param float $default_timeout time in milliseconds
     */
    public function __construct(string $hostname, string $scope, bool $secure = true, float $default_timeout = 10000)
    {
        parent::__construct($hostname, $scope, $secure, $default_timeout);
        $this->client = new \GSuite\V1\DomainServiceClient($hostname, $this->getClientOptions());
    }
    
    /**
     * Auth wrapper for \GSuite\V1\DomainServiceClient::VerifyDomain
     * @param \Gsuite\V1\VerifyDomainRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\VerifyDomainResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function VerifyDomain(\Gsuite\V1\VerifyDomainRequest $req, array $options = []): \Gsuite\V1\VerifyDomainResponse
    {
        return $this->doRequest(
            array($this->client, 'VerifyDomain'),
            $req,
            $options
        );
    }
    
}
