<?php 
# Code generated by sdkgen
# Generated on 2025-04-08 20:28:47.560715719 +0000 UTC using container gcr.io/repcore-prod/sdkgen:16.115.0
# DO NOT EDIT!
namespace Vendasta\GSuite\V1\internal;

use Vendasta\GSuite\V1\Config;

class DomainServiceGeneratedClient
{
    private $transport;
    
    /**
     * DomainServiceGeneratedClient constructor.
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     */
    public function __construct(string $env, float $default_timeout = 10000)
    {
        $this->transport = $this->getTransportClient($env, $default_timeout);
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     * @return DomainServiceClientInterface
     */
    private function getTransportClient(string $env, float $default_timeout = 10000): DomainServiceClientInterface
    {
        $config = $this->getEnvConfig($env);

        if (class_exists('Grpc\ChannelCredentials', true)) {
            return new DomainServiceGRPCClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        } else {
            return new DomainServiceHTTPClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        }
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @return array
     */
    private function getEnvConfig(string $env): array {
        return Config::ENVIRONMENT_PARAMS[$env];
    }
    
    /**
     * @param \Gsuite\V1\VerifyDomainRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\VerifyDomainResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function VerifyDomain(\Gsuite\V1\VerifyDomainRequest $req, array $options = []): \Gsuite\V1\VerifyDomainResponse
    {
        return $this->transport->VerifyDomain($req, $options);
    }
    
}
