<?php 
# Code generated by sdkgen
# Generated on 2020-07-21 20:19:09.857747509 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!

namespace Vendasta\GSuite\V1\internal;

use Vendasta\Vax\HTTPClient;

class GSuitePartnerHTTPClient extends HTTPClient implements GSuitePartnerClientInterface
{
    /**
     * GSuitePartnerHTTPClient constructor.
     * @param string $host
     * @param string $scope
     * @param bool $secure
     * @param float $default_timeout
     */
    public function __construct(string $host, string $scope, bool $secure = true, float $default_timeout = 10000)
    {
        parent::__construct($host, $scope, $secure, $default_timeout);
    }
    
    /**
     * Auth wrapper for \GSuite\V1\GSuitePartnerClient::GetDomainAvailability
     * @param \Gsuite\V1\GetDomainAvailabilityRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetDomainAvailability(\Gsuite\V1\GetDomainAvailabilityRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->doRequest(
            "/gsuite.v1.GSuitePartner/GetDomainAvailability",
            $req,
            "\Google\Protobuf\GPBEmpty",
            $options
        );
    }
    
    /**
     * Auth wrapper for \GSuite\V1\GSuitePartnerClient::VerifyDomain
     * @param \Gsuite\V1\VerifyDomainRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\VerifyDomainResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function VerifyDomain(\Gsuite\V1\VerifyDomainRequest $req, array $options = []): \Gsuite\V1\VerifyDomainResponse
    {
        return $this->doRequest(
            "/gsuite.v1.GSuitePartner/VerifyDomain",
            $req,
            "\Gsuite\V1\VerifyDomainResponse",
            $options
        );
    }
    
    /**
     * Auth wrapper for \GSuite\V1\GSuitePartnerClient::GetDomainInformation
     * @param \Gsuite\V1\GetDomainInformationRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\GetDomainInformationResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetDomainInformation(\Gsuite\V1\GetDomainInformationRequest $req, array $options = []): \Gsuite\V1\GetDomainInformationResponse
    {
        return $this->doRequest(
            "/gsuite.v1.GSuitePartner/GetDomainInformation",
            $req,
            "\Gsuite\V1\GetDomainInformationResponse",
            $options
        );
    }
    
}
