<?php 
# Code generated by sdkgen
# Generated on 2020-10-07 16:06:52.401010677 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!

namespace Vendasta\GSuite\V1\internal;

use Vendasta\Vax\HTTPClient;

class PartnerHTTPClient extends HTTPClient implements PartnerClientInterface
{
    /**
     * PartnerHTTPClient constructor.
     * @param string $host
     * @param string $scope
     * @param bool $secure
     * @param float $default_timeout
     */
    public function __construct(string $host, string $scope, bool $secure = true, float $default_timeout = 10000)
    {
        parent::__construct($host, $scope, $secure, $default_timeout);
    }
    
    /**
     * Auth wrapper for \GSuite\V1\PartnerClient::ListSubscriptions
     * @param \Gsuite\V1\ListSubscriptionsRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\ListSubscriptionsResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListSubscriptions(\Gsuite\V1\ListSubscriptionsRequest $req, array $options = []): \Gsuite\V1\ListSubscriptionsResponse
    {
        return $this->doRequest(
            "/gsuite.v1.Partner/ListSubscriptions",
            $req,
            "\Gsuite\V1\ListSubscriptionsResponse",
            $options
        );
    }
    
}
