<?php 
# Code generated by sdkgen
# Generated on 2020-10-07 16:06:52.401010677 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!
namespace Vendasta\GSuite\V1\internal;

use Vendasta\GSuite\V1\Config;

class PartnerGeneratedClient
{
    private $transport;
    
    /**
     * PartnerGeneratedClient constructor.
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     */
    public function __construct(string $env, float $default_timeout = 10000)
    {
        $this->transport = $this->getTransportClient($env, $default_timeout);
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     * @return PartnerClientInterface
     */
    private function getTransportClient(string $env, float $default_timeout = 10000): PartnerClientInterface
    {
        $config = $this->getEnvConfig($env);

        if (class_exists('Grpc\ChannelCredentials', true)) {
            return new PartnerGRPCClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        } else {
            return new PartnerHTTPClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        }
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @return array
     */
    private function getEnvConfig(string $env): array {
        return Config::ENVIRONMENT_PARAMS[$env];
    }
    
    /**
     * @param \Gsuite\V1\ListSubscriptionsRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Gsuite\V1\ListSubscriptionsResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListSubscriptions(\Gsuite\V1\ListSubscriptionsRequest $req, array $options = []): \Gsuite\V1\ListSubscriptionsResponse
    {
        return $this->transport->ListSubscriptions($req, $options);
    }
    
}
